version: '2'

services:
  kafka_monitor:
    image: istresearch/scrapy-cluster:kafka-monitor-ci-dev
    build:
      context: .
      dockerfile: docker/kafka-monitor/Dockerfile.py3
    depends_on:
      - kafka
      - redis
    restart: always
  redis_monitor:
    image: istresearch/scrapy-cluster:redis-monitor-ci-dev
    build:
      context: .
      dockerfile: docker/redis-monitor/Dockerfile.py3
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
  crawler:
    image: istresearch/scrapy-cluster:crawler-ci-dev
    build:
      context: .
      dockerfile: docker/crawler/Dockerfile.py3
    depends_on:
      - kafka
      - redis
      - zookeeper
#    volumes:
#      - /home/suzuki/src/scrapy-cluster/crawler:/usr/src/app
    volumes:
       - /home/suzuki/src/scrapy-cluster/twisted:/usr/local/lib/python3.6/site-packages/twisted
       - /home/suzuki/src/scrapy-cluster/scrapy:/usr/local/lib/python3.6/site-packages/scrapy
       - /home/suzuki/src/scrapy-cluster/crawler:/usr/src/app
       - /home/suzuki/src/scrapy-cluster/docker/crawler/settings.py:/usr/src/app/crawling/localsettings.py
       - /home/suzuki/src/scrapy-cluster/utils/scutils:/usr/local/lib/python3.6/site-packages/scutils
    restart: always
  rest:
    image: istresearch/scrapy-cluster:rest-ci-dev
    build:
      context: .
      dockerfile: docker/rest/Dockerfile.py3
    depends_on:
      - kafka
      - redis
    restart: always
    ports:
      - "5343:5343"
  redis:
    image: redis
    # command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
